### ISSUE TITLE
ER図

### ISSUE THREAD

**Issue by Takahiro800** [Takahiro800/qiita_clone1#4]
![2019-09-04 4 22のイメージ](https://user-images.githubusercontent.com/52635809/64202296-c62c8480-cecb-11e9-81f7-05fd931242ae.jpg)

**Comment by yuta-ushijima** [comment]
一度まずは以下の記事をご一読いただけると！

https://esa-pages.io/p/sharing/11912/posts/38/e093fc6d8f01150f1951.html

また、users_idとuser_idのようになっている箇所があるのですが、こちらは何か特別な意図がありますか？
特になければuser_idの方は削除しちゃってもいいかなと。

created_atとupdated_atについては自動的に生成されるので記述しなくてもいいですが、もし記述するなら他のテーブルにも記載した方がいいですね。

**Comment by Takahiro800** [comment]
![2019-09-05 5 16のイメージ](https://user-images.githubusercontent.com/52635809/64288213-7e296280-cf9c-11e9-9235-d629d4e1299f.jpg)

ご指摘ありがとうございました
修正しました

**Comment by yuta-ushijima** [comment]
いいですね！良さそうです！
